### ISSUE TITLE
fix(dialog): make action buttons to look like outline buttons

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-bootstrap#145]

**Comment by lkarakoleva** [comment]
Dialog and dialog-like windows used in components should have the same interaction states of action buttons (outline buttons styles)

Normal state
.btn-outline-primary {
    color: #0275d8;
    background-image: none;
    background-color: transparent;
    border-color: #0275d8;

Use the correct hover back ground color for primary button
.btn-outline-primary:hover {
    color: #fff;
    background-color: #0275d8;
    border-color: #0275d8;

Dialog-like window (spreadsheet) - correct
<img width="327" alt="screen shot 2017-05-23 at 11 44 27 am" src="https://cloud.githubusercontent.com/assets/16577622/26346214/2b39fd3a-3fae-11e7-931e-e0492979da18.png">

Dialog  - incorrect
<img width="464" alt="screen shot 2017-05-23 at 11 44 50 am" src="https://cloud.githubusercontent.com/assets/16577622/26346218/2e2ef39c-3fae-11e7-9261-bb9c3e5502d0.png">

**Comment by joneff** [comment]
Needs https://github.com/telerik/kendo-theme-default/pull/689 and https://github.com/telerik/kendo-theme-bootstrap/pull/301 in that order
