### ISSUE TITLE
Visual glitches

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-theme-bootstrap#194]
MaskedTextBox is without border, black Grid borders, ScrollView is too small while, we have huge empty space beneath the grid.
![capture 2017-04-04 at 10 35 13](https://cloud.githubusercontent.com/assets/4143177/24994840/3b5c3978-2035-11e7-9499-b52221f83e2e.png)

**Comment by mvgmvg** [comment]
Instead of increasing scroll view width, @lkarakoleva gave me better images to use them in the widget.

**Comment by Dimitar-Goshev** [comment]
Issues are no longer reproducible.
