### ISSUE TITLE
Component files do not reference the bootstrap variables

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-bootstrap#196]
The all.scss file includes the bootstrap variables, but standalone files do not. Because of this, the following code does not work:

    @import "~@progress/kendo-theme-bootstrap/scss/panelbar";

The workaround is to include the bootstrap vars prior to the component file:

    @import "~bootstrap/scss/variables";
    @import "~@progress/kendo-theme-bootstrap/scss/panelbar";

Since the bootstrap vars are declared with `!default` clauses, we can safely add them to every component file, so that this requirement is removed.

**Comment by joneff** [comment]
Fixed by c32e78944512a514fcf2f401229d0e532ae443f6
