### ISSUE TITLE
Bootstrap - add new color - primary contrast 

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-theme-bootstrap#199]
Primary contrast color is needed if primary color (background) is light and contrast text color should be calculated. 
In Theme Builder contrast primary color is needed for Hight contrast swatch - primary color is white, text color is white and can't be change of the user:
![high-contrast](https://cloud.githubusercontent.com/assets/16577622/25275650/07e66e4a-269f-11e7-9472-7ac8a1ca6410.png)

**Comment by joneff** [comment]
Fixed by https://github.com/telerik/kendo-theme-default/pull/546
