### ISSUE TITLE
Wrong MultiSelect border color

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-theme-bootstrap#202]
1. Go to http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/multiselect/index
![image](https://cloud.githubusercontent.com/assets/6614183/25335071/12bcfef8-28fa-11e7-8111-406efe69599f.png)

**Comment by inikolova** [comment]
Can be observed in the Kendo UI for Angular 2 demos -> http://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/
