### ISSUE TITLE
TreeList / Grid row is higher than expected

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-theme-bootstrap#207]
URL: kendo-ui/grid/editing-inline

Row should be 48px high, but it is 62px. If Edit mode is entered, row height becomes correct:
![image](https://cloud.githubusercontent.com/assets/6614183/25382445/59767934-29c0-11e7-81da-4cdc5da2e255.png)

**Comment by theOrlin** [comment]
Test using latest version of Treelist code.
