### ISSUE TITLE
Grid issues.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-theme-bootstrap#218]
- [x] **1. Grid pager padding is 5px by Theme-Guides but it is set to 6px.**

Please refer to the following screenshot: 
![image](https://cloud.githubusercontent.com/assets/11087921/25439199/72dd599e-2aa4-11e7-8d1c-f675d0672b85.png)

- [ ] **2. Row filter in the Grid demo has cut input and not centered filter icon.**
Please refer tp to the following screenshot:

![image](https://cloud.githubusercontent.com/assets/11087921/25439344/e2ba1de2-2aa4-11e7-9f91-2fc48e9465f3.png)

http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/grid/filter-row

- [x] **3. **The Grid frozen column demo is broken.****

Please check the demo: http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/grid/frozen-columns

- [x] **4. When the Grid cell is in edit mode(incell editing) the whole row is shrinking a little bit.**

Please try to edit one of the cells to observe the undesired result:

http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/grid/editing

- [x] **5. The Grid column menu has unexpected white space at the top and at the bottom.**

Please refer to the following screenshot:

![image](https://cloud.githubusercontent.com/assets/11087921/25440773/1446bfe2-2aa9-11e7-9641-3fd5f3c7a65c.png)

- [x] **6. The Grid validation messages are rendered inside the cells.**

Please refer to the following screenshot:

![image](https://cloud.githubusercontent.com/assets/11087921/25440930/86d4b870-2aa9-11e7-9574-b28f9a281fdc.png)

- [x] **7. The Grid does not indicate visually the focused cell during keyboard navigation.**

Please refer to the demo: http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/grid/keyboard-navigation

- [x] **8. When ColumnMenu is enabled, the column names in the grid header are not vertically aligned
Grid demo: grid/column-menu**
![untitled](https://cloud.githubusercontent.com/assets/5861835/25666197/7b12b102-3028-11e7-9541-899401497d1d.png)

There is also header **padding: .75rem;** which is probably unnecessary

- [x] **9. The NumericTextBox in the ColumnMenu's filter is broken. Grid demo: grid/column-menu**
![untitled](https://cloud.githubusercontent.com/assets/5861835/25666336/f46bac8e-3028-11e7-9612-650af60fd9f0.png)

- [x] **10. Export loading indicator is shown on wrong position** - https://github.com/telerik/kendo-theme-default/issues/614
![untitled](https://cloud.githubusercontent.com/assets/5861835/25667413/099d010e-302c-11e7-9286-db72287c1081.png)

- [x] **11. Redundant border is shown in the footer**
![untitled](https://cloud.githubusercontent.com/assets/5861835/25667502/550b25c6-302c-11e7-8d69-9e0e6149f60e.png)

- [x] **12. Red border is flickering over textbox editors when they enter edit mode on the Inline Editing demo**

**Comment by theOrlin** [comment]
Cell focus state fixed by https://github.com/telerik/kendo-theme-bootstrap/pull/247

**Comment by theOrlin** [comment]
.9 also applies to Theme Default

**Comment by theOrlin** [comment]
.8 also applies to Theme-Default

**Comment by theOrlin** [comment]
As for 1, the current theme guidelines are wrong. Contacted @yordanov and got a confirmation that the design is due for an update. The intended padding of the Grid pager is 6px or .375rem.

**Comment by theOrlin** [comment]
12 is not a theme-related issue - https://github.com/telerik/kendo/issues/7364

**Comment by matanasov** [comment]
2. We still have one of the editors cut off.

**Comment by theOrlin** [comment]
Numeric spinners fixed by https://github.com/telerik/kendo-theme-default/pull/664

**Comment by theOrlin** [comment]
The missing border of the autocomplete will be fixed by a pending merge of branch https://github.com/telerik/kendo/tree/remove-k-header-from-pickers removing the .k-header class.
