### ISSUE TITLE
The items text is carried into two lines in vertical menu in case there is a space

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-bootstrap#226]
### Bug report
The items text is carried into two lines in vertical menu in case there is a space
![image](https://cloud.githubusercontent.com/assets/7202037/25442388/9602ef20-2aad-11e7-88af-c6d86929c855.png)

**Comment by mvgmvg** [comment]
The described behavior is expected - An item with longer text should wrap to the next line (consulted with @yordanov ). If width of the menu is enough, text will not wrap.
