### ISSUE TITLE
Items height is smaller in context menu

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-bootstrap#227]
### Bug report
Items height is smaller in context menu
![image](https://cloud.githubusercontent.com/assets/7202037/25442581/18460e04-2aae-11e7-9a7a-492688f62a3c.png)

### Expected:
The items height is similar to the menu items height
![image](https://cloud.githubusercontent.com/assets/7202037/25442701/6736b2ca-2aae-11e7-9ba8-9c0c58da0184.png)

**Comment by joneff** [comment]
That's expected http://v4-alpha.getbootstrap.com/components/navbar/#nav

**Comment by mparvanov** [comment]
The issue is rather related to the inconsistency between the items height in the Menu compared to the height in the ContextMenu items:
<span class="k-link">Sub Sub 1</span> 

Menu: 66px x 21px
ContextMenu: 66px x 16px

Sample setup
```
<body>
  
             <ul id="menu1">
                 <li>Item 1
               <ul>
                     <li>Sub Sub 1</li>
                     <li>Sub Sub 2</li>
                     <li>Sub Sub 3</li>
                   </ul></li>
                 <li>Item 2</li>
                 <li>Item 3</li>
                 <li>Item 4</li>
             </ul>
 <div id="target">Target</div>

             <ul id="context-menu">
                 <li>Item 1
                   <ul>
                     <li>Sub Sub 1</li>
                     <li>Sub Sub 2</li>
                     <li>Sub Sub 3</li>
                   </ul>
                 </li>
                 <li>Item 2</li>
                 <li>Item 3</li>
                 <li>Item 4</li>
             </ul>
           <script>
            $("#context-menu").kendoContextMenu({
                target: "#target",
              orientation: "horizontal"
            }).data("kendoContextMenu").wrapper.css("width", 400);;
         
           $("#menu1").kendoMenu({
              orientation: "horizontal"
            });
        </script>
</body>
```

**Comment by mparvanov** [comment]
The issue is not happening in case the same line-height is set to the context menu target.
