### ISSUE TITLE
How to deal with focus state

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-bootstrap#23]
Here is how bootstrap handles focus:
- inputs: dropshadow
- everything else: native focus (outline)

Kendo, on the other hand, uses inner shadow to denote focus. Also, in kendo there is a difference between currently focused widget (say treeview) and the item currently active widget.

So the questions are:
- should we use outline or inner shadow for focused items
- should we have outline on larger widgets (treeview, per say)

/cc @gyoshev @underlog @inikolova

**Comment by gyoshev** [comment]
If we are aiming for consistency with Bootstrap, the outline may do the trick. Regarding the outline for larger widgets, how would it look if there is a focused item in the treeview?

**Comment by joneff** [comment]
Currently, it looks like this:

![image](https://cloud.githubusercontent.com/assets/8048/15857811/f2c61714-2cc5-11e6-9c01-0895e02ffe25.png)

When we agree on something, it should look something like:

![image](https://cloud.githubusercontent.com/assets/8048/15857877/52bc4724-2cc6-11e6-9de9-54769cef8eaa.png)

I guess we could "normalize" the outline, since each browser does it a bit differently.
