### ISSUE TITLE
TreeList issues

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-theme-bootstrap#232]
- [ ] **1. The cell with validation flashes in red when the row is set in edit mode.**

Please refer to the video:  https://www.screencast.com/t/OWLwPv8SH

- [x] **2.  When the TreeList row is in edit mode(inline editing) the whole row is shrinking a little bit.**

Please try to edit one of the rows to observe the undesired result:  http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/treelist/editing

- [x] **3. The TreeList column menu has unexpected white space at the top and at the bottom.**
Please refer to the following screenshot:
![image](https://cloud.githubusercontent.com/assets/11087921/25481427/c5ff3e10-2b55-11e7-8868-19236b42bf50.png)

- [x] **4. The frozen columns demo is broken:** 

Please check the demo: http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/treelist/frozen-columns

**Comment by matanasov** [comment]
Issues 2,3 and 4 are fixed.
1 is still pending

**Comment by theOrlin** [comment]
The red flashing of the input with set validation is due to the animation transitions. Will need a designer's OK before we get rid of them.

@lkarakoleva @yordanov

**Comment by yordanov** [comment]
I find it strange and definitely not user friendly to have an invalid state prior to user input. I guess this is related to how the validation works, but it is really **weird to have initially invalid inputs e.g. when you are about to add a "New record"**. In this case inputs should become invalid only after the "Create/Update" button is clicked. 

I don't know if we can fix this, but to me this is the actual bug, not the transition animation from invalid to normal state.

In case we cannot fix this and the is really no way to fix it, I'd suggest we remove the `border-color` animation only, not the whole transition. 

Again, to me this is validation behavior issue, not a styling one!

**Comment by theOrlin** [comment]
1 is not a theme-related issue - https://github.com/telerik/kendo/issues/7364
