### ISSUE TITLE
PivotGrid issues

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-theme-bootstrap#236]
- [x] **1. Rows are misaligned. - https://github.com/telerik/kendo-theme-default/issues/633**

The issue can be observed in the index demo after expanding the All Geographies and scrolling down. Please refer to the image:  
![2017-05-02_1755](https://cloud.githubusercontent.com/assets/3042944/25624234/7357695c-2f61-11e7-8444-1917bdda7550.png)

- [x] **2. KPI icon for -1 does not look consistent with the icon in rest of the skins. It is a simple black square. **
The issue can be observed in the KPI Measures demo and sort the [Date].[Calendar] column in descending order. Please refer to the image below: 
![2017-05-03_1846](https://cloud.githubusercontent.com/assets/3042944/25669467/48f59a18-3032-11e7-9dba-2029d65c4962.png)

- [x] **3. Overlapping icons in PDF export of the PivotGrid.** - https://github.com/telerik/kendo-theme-default/issues/642
Please refer to the image below that shows the exported document: 
![2017-05-03_1900](https://cloud.githubusercontent.com/assets/3042944/25669717/081780e6-3033-11e7-8b7f-ac1d6d2195de.png)

**Comment by hadjieva** [comment]
- [ ] **4. Include Fields in PivotGrid FieldMenu has unnecessary padding when sorting is not enabled**
Image: https://www.screencast.com/t/rxSFiBna 
Example: http://dojo.telerik.com/EcUQop

**Comment by joneff** [comment]
@hadjieva 2) should be it's own separate issue -- we need separate icons for pivot KPI status and trends:
```
.k-i-kpi-status-open | hold | denied
.k-i-kpi-trend-increase | decrease | equal
```

**Comment by joneff** [comment]
Needs https://github.com/telerik/kendo/pull/7518 and https://github.com/telerik/kendo-theme-default/pull/691 in that order.
