### ISSUE TITLE
Progress bar is not shown.

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-theme-bootstrap#242]
This is the progress bar in BootstrapV3:
![bootstrapv3](https://cloud.githubusercontent.com/assets/5861835/25710875/3e92e34a-30f6-11e7-9bae-4e5a9751929c.png)

And this is the progress bar in BootstrapV4:
![bootstrapv4](https://cloud.githubusercontent.com/assets/5861835/25710881/426f0a48-30f6-11e7-89aa-07935e1e2dc6.png)

**Comment by theOrlin** [comment]
Fixed along with https://github.com/telerik/kendo-theme-default/issues/481
