### ISSUE TITLE
Bootstrap global options not respected. e.g. $enable-rounded

### ISSUE THREAD

**Issue by cornillemichiel** [telerik/kendo-theme-bootstrap#245]
Bootstrap 4 _variables.scss contains some global options 

```
// Options
//
// Quickly modify global styling by enabling or disabling optional features.

$enable-rounded:            true !default;
$enable-shadows:            false !default;
$enable-gradients:          false !default;
$enable-transitions:        true !default;
$enable-hover-media-query:  false !default;
$enable-grid-classes:       true !default;
$enable-print-styles:       true !default;
```

e.g.setting $enable-rounded:false doesn't result in rounded borders disappearing from Kendo controls.

It is used in the border radius mixin. which can be found  [here](https://github.com/twbs/bootstrap/blob/890c6041f3bf70b76244611916bc1286a8150bd5/scss/mixins/_border-radius.scss)

For enable-rounded, the following could suffice: I would PR it but I dont know where this sort of code belongs.

```
@if not($enable-rounded) {
    $border-radius: 0;
}
```

**Comment by gyoshev** [comment]
Thank you for the feedback! It seems like a great idea to play nice with these flags, where applicable. The logic feels most appropriate for [`scss/_variables.scss`](https://github.com/telerik/kendo-theme-bootstrap/blob/master/scss/_variables.scss#L39), where we store root-level variable definitions.
