### ISSUE TITLE
theme only works with webpack

### ISSUE THREAD

**Issue by EdCharbeneau** [telerik/kendo-theme-bootstrap#256]
The ~ path operator does not work in other sass compilers. Using something like node-sass causes missing file errors. This means kendo-bootstrap-theme is only able to be used in development stacks that include webpack.

A sample of this issue can be found here.
https://github.com/EdCharbeneau/kui-bootstrap-issue

**Comment by tsvetomir** [comment]
It looks like we need something like [node-sass-tilde-importer](https://www.npmjs.com/package/node-sass-tilde-importer) to be able to import the default theme in this case. Perhaps we should document this workflow.

**Comment by EdCharbeneau** [comment]
If that's the fix we choose then it needs to be documented in all Kendo UI based products that may use this theme.

**Comment by EdCharbeneau** [comment]
Research needs to be done to insure this works with other compilers as well. Node Sass was just the example I used. Is there any way to fix the paths in the source code?

**Comment by eeasss** [comment]
We will update the docs with instructions on how to apply imports to the most popular ass compilers.

**Comment by tsvetomir** [comment]
The alternative would be to distribute a copy of the base "default" theme along with this one. This will remove the need to reference a node module for it to work. /cc @gyoshev

**Comment by gyoshev** [comment]
@tsvetomir do you mean distributing it as part of the NPM package? This might just work -- we will also need to copy the [default bootstrap variables](https://github.com/telerik/kendo-theme-bootstrap/blob/develop/scss/_variables.scss#L2). It costs an additional build step, but it might make the source distribution easier to use.

**Comment by joneff** [comment]
@tsvetomir we don't really need a copy of the entire theme: we need the mixins, the layout files and probably few more tricky files. Like @gyoshev it's going to be an additional step

**Comment by tsvetomir** [comment]
Seems legit. This can all happen at build-time without polluting the repo.

**Comment by gyoshev** [comment]
Version `2.5.1` of kendo-theme-bootstrap now ships without the tilde paths, and can be used without webpack. Tested with the provided app and with the `sass` ruby gem. :tada:
