### ISSUE TITLE
Grid form elements cause increased row height in edit modes

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-theme-bootstrap#279]
Related to 4 in https://github.com/telerik/kendo-theme-bootstrap/issues/218

The size of the buttons and form elements in inline edit mode of the Grid cause increased row size when in batch edit and inline edit mode. By design, row size should be 48px.

Issue also applies to Default SASS theme with its corresponding row size.

**Comment by MilenaCh** [comment]
Validation messages of Grid's editors are not completely visible in Firefox:
Steps:
1.Navigate to batch editing demo against latest version of Bootstrap theme.
2.Add new record
3.Enter value in productname cell
4.Blur outside the cell
5.Delete the new value from productname cell
6.Blur outside the cell
Result:
https://www.screencast.com/t/Nvn3eHsH799  - latest version
https://www.screencast.com/t/DZJqu6I4wLb - 2017.2.621

Valid for default and bootstrap sass themes also.

**Comment by MilenaCh** [comment]
Grid's numeric editors have no а proper width:
Expected: textbox cover the whole cell
Actual: https://www.screencast.com/t/HDN3RsV26l
