### ISSUE TITLE
Undefined variables when individual files are imported

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-bootstrap#285]
The following imports:

@import "\~bootstrap/scss/variables";
@import "\~@progress/kendo-theme-bootstrap/scss/switch";

... lead to a JavaScript error in the SASS loader:

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./\~/css-loader!./\~/sass-loader!./src/app/main/trial.component.scss
Module build failed: 
undefined
            ^
      Undefined variable: "$disabled-opacity".

Reported in ticket ID: 1118809

**Comment by gyoshev** [comment]
The most robust solution would be to include the variables from kendo-theme-default after defining the kendo-theme-bootstrap variables. This way all default values from kendo-theme-default will be inferred.
