### ISSUE TITLE
The numeric textbox spinners have incorrect width inside the grid filter row and disappear if value is entered.

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-theme-bootstrap#295]
This is valid only for Edge browser
1. Incorrect width:
![spinners1](https://user-images.githubusercontent.com/5861835/28676950-c99cad1e-72f4-11e7-8d79-c0558f1501ff.png)

2. Disappear when value is entered.
![spinners2](https://user-images.githubusercontent.com/5861835/28677421-1e82517a-72f6-11e7-872e-71d872104e41.png)

**Comment by theOrlin** [comment]
This is also valid for theme Default 2.0
