### ISSUE TITLE
Error importing @progress/kendo-theme-bootstrap/scss/all

### ISSUE THREAD

**Issue by Gambero81** [telerik/kendo-theme-bootstrap#297]
I'm using version 2.6.2 but same problem with 2.7.0-dev.201708071301.

in my app scss file i have imported kendo bootstrap scss:
@import 'node_modules/ @progress /kendo-theme-bootstrap/scss/all';

but it result in a scss compiler error:
argument `$color` of `rgba($color, $alpha)` must be a color

Backtrace:
	node_modules/ @progress /kendo-theme-bootstrap/modules/bootstrap/scss/_variables.scss:408, in function `rgba`

what's wrong?
Thanks

**Comment by joneff** [comment]
The variable in question is placeholder for gradient. This particular gradient has been set to `none`. Our mixins check against certain keywords to ensure that the proper gradient or no gradient is set.

That being said, it's quite odd that you see the error in question. Could you share more details how you are building the theme, say version of theme-default (theme-bootstrap depends on it), type of sass compiler you are using and it's version e.g. node-sass or ruby-sass etc, as well as other information you find relevant?

**Comment by joneff** [comment]
Disregard my previous comment. The issue may happen if you depend on a different version of bootstrap, say v4-beta. Make sure you use the correct version, as specified in package.json.

**Comment by Gambero81** [comment]
I have installed bootstrap version specified in package.json (git://github.com/twbs/bootstrap.git#95f37e4c402df37db16781995ffa1592032df9c8)

![kendobootstrap1](https://user-images.githubusercontent.com/13186600/30022378-642c68e4-916b-11e7-953c-d2d0a6b8e1ca.png)

but error still present:

![kendobootstrap2](https://user-images.githubusercontent.com/13186600/30022407-812aa1cc-916b-11e7-9088-774043191e5f.png)

to compile scss i use a visual studio addin named "Web Compiler"
[https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebCompiler](url)

in my scss i declare:

@import 'node_modules/@progress/kendo-theme-bootstrap/scss/all';

same error if i declare:

@import 'node_modules/bootstrap/scss/bootstrap';

or

@import 'node_modules/bootstrap/scss/bootstrap';
@import 'node_modules/@progress/kendo-theme-bootstrap/scss/all';

**Comment by Gambero81** [comment]
@joneff have you been able to reproduce the problem?
Thanks

**Comment by mrmashal** [comment]
You should use `all.css` from the `dist` directory:

```css
@import 'node_modules/@progress/kendo-theme-bootstrap/dist/all';
```
