### ISSUE TITLE
Multiselect issues related to bootstrap v4 update

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-bootstrap#315]
* [x] remove focus outline of remove token link
* [x] missing hover state of tokens
* [x] clear input icon is not aligned

Part of #298

**Comment by joneff** [comment]
Needs https://github.com/telerik/kendo-theme-default/pull/719 and #321

**Comment by Dimitar-Goshev** [comment]
- Clear icon is still misaligned:
![image](https://user-images.githubusercontent.com/6614183/30321069-695517dc-97bd-11e7-8f18-9225da5a12a4.png)
