### ISSUE TITLE
When in Grid's filter, DatePicker's icon is not fully displayed in IE11

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-theme-bootstrap#318]
See the images bellow

Filter Menu:

![filtermenubootstrap](https://user-images.githubusercontent.com/5861835/30056694-5f8f0d92-923c-11e7-8f62-720c540d15a1.png)

Filter Row

![filterrowbootstrap](https://user-images.githubusercontent.com/5861835/30056703-64ddbb68-923c-11e7-9e84-d0205f1e94e9.png)

**Comment by joneff** [comment]
* Partially targeted by 3c251a7e1594a2436f516306761226c5a9f9b924.
* Needs https://github.com/telerik/kendo-theme-default/pull/722 for complete fix.
