### ISSUE TITLE
Pager is misaligned when page font-size is 14px

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-bootstrap#327]
![image](https://user-images.githubusercontent.com/90405/30419788-4be194bc-9940-11e7-9eec-3cc95ed33264.png)

Reproducible when the grid example is opened in the Dojo, or in the Angular examples. Dojo link: http://dojo.telerik.com/@gyoshev/UyEmu

Icons remain at 16px, link items inherit the page font-size.

**Comment by joneff** [comment]
The pager uses `align-items: center`. If we switch it to `stretch` buttons should be fine.

**Comment by joneff** [comment]
Add a test for pager with different inline font-size
