### ISSUE TITLE
Gantt views dropdown is not vertically aligned with smaller resolution

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-bootstrap#337]
The issue could be observed with smaller width on the following demo:
http://demos.telerik.com/kendo-ui/gantt/index

![image](https://user-images.githubusercontent.com/7202037/31537431-ca0fe452-b00a-11e7-8575-21c9e2738250.png)

**Comment by Dimitar-Goshev** [comment]
Not reproducible with R3 2018 (2018.3.911)
