### ISSUE TITLE
Success variable does not update Success Notification after upgrade to Bootstrap v4 beta

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-theme-bootstrap#340]
The issue is reproducible in ThemeBuilder app by changing the Success variable - Success Notification is not updated.

**Comment by joneff** [comment]
Fixed by 16f7c34eb28bb76e2f08106f049b62122b2ab094

**Comment by joneff** [comment]
Note, themebuilder should be updated in order to see this in action
