### ISSUE TITLE
Kendo Theme Bootstrap is not compatible with bootstrap v4.0.0-beta.2

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-theme-bootstrap#341]
When building the project the following error is thrown:

Error: $popover-arrow-outer-width:           ($popover-arrow-width + 1px) !default;
                                     ^
      Incompatible units: 'px' and 'rem'.
      in /Users/crash/git/traveliko/traveliko-spa-administration/node_modules/@progress/kendo-theme-bootstrap/modules/bootstrap/scss/_variables.scss (line 680, column 39)
    at options.error (/Users/crash/git/traveliko/traveliko-spa-administration/node_modules/node-sass/lib/index.js:291:26)

A workaround for the issue is to downgrade bootstrap to v4.0.0-beta.

**Comment by kibbled** [comment]
I would argue this is an urgent bug as it breaks your build if you are using SCSS.

**Comment by gyoshev** [comment]
Due to the tight integration between the theme and the bootstrap framework, there is always the risk for broken compatibility, especially before the final 4.0 version is released. Especially during the beta, make sure to use the version that is [listed as a peer dependency](https://github.com/telerik/kendo-theme-bootstrap/blob/develop/package.json#L69), until we claim support for the newly released Bootstrap version.

**Comment by kibbled** [comment]
One suitable workaround is to define the $popover-arrow-outer-width variable in your SCSS file before importing Kendo.

`$popover-arrow-outer-width: ($popover-arrow-width + rem-calc(1px)) !default;`

**Comment by mbrookson** [comment]
This is still broken in the latest version with the final release of bootstrap 4. The above suggestion does still work as a fix but would be good to not have to do that.

**Comment by gyoshev** [comment]
@mbrookson I could not reproduce the problem with the latest version. Here is what I tried:

```scss
// test.scss
@import "node_modules/bootstrap/scss/bootstrap";
@import "node_modules/@progress/kendo-theme-bootstrap/scss/all";
.test { color: red; }
```
```bash
npm install @progress/kendo-theme-bootstrap bootstrap node-sass
npx node-sass ./test.scss
```

`npm ls` shows the following package versions:

```
@progress/kendo-theme-bootstrap@2.11.9
└ @progress/kendo-theme-default@2.49.0
bootstrap@4.0.0
node-sass@4.7.2
```
