### ISSUE TITLE
Theme does not get applied properly

### ISSUE THREAD

**Issue by codehippie1** [telerik/kendo-theme-bootstrap#344]
I have customized bootstrap theme and loaded them in variables.css and included before importing kendo-bootstrap-theme

```
@import "variables"; /*Contains the downloaded variable created using bootstrap theme builder.*/
@import "~bootstrap/scss/bootstrap";
@import "~@progress/kendo-theme-bootstrap/scss/all";
```

Contents of downloaded variable.scss
```
$base-theme: Bootstrap;
$skin-name: t-latest;
$accent: #8cc63f;
$secondary: #005596;
$info: #5bc0de;
$success: #5cb85c;
$warning: #ffbb5b;
$error: #e3470e;
$body-bg: #ffffff;
$body-color: #000000;
$component-bg: #f5f5f5;
$component-color: #1c3a4c;
$card-cap-bg: #4189c7;
$card-cap-color: #ffffff;
$series-a: #d26e46;
$series-b: #ac941c;
$series-c: #40a9e3;
$series-d: #016a98;
$series-e: #7a8c95;
$series-f: #355261;
```

Unfortunately, the styles are getting applied only partially. Button color is still grey(#f6f6f6), Grid column header are black and not bold.

**Comment by joneff** [comment]
To quote the related ticket (https://github.com/telerik/kendo-angular/issues/1042#issuecomment-340355227)

>To resolve the problem, include the kendo-theme-bootstrap source before importing bootstrap:
>
>```scss
>@import "variables";
>@import "~@progress/kendo-theme-bootstrap/scss/all";
>@import "~bootstrap/scss/bootstrap";
>```
>
>This way the variables from the ThemeBuilder are expanded correctly, before compiling the Bootstrap framework.

**Comment by gyoshev** [comment]
Closing this, as it is added in the documentation.
