### ISSUE TITLE
Add styles for grid adaptive rendering

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-theme-bootstrap#358]
Requested in ticket ID 1146171. 

The mobile styles we have for the LESS themes are necessary so the Kendo UI Grid can be responsive. 

[https://docs.telerik.com/kendo-ui/controls/data-management/grid/adaptive](https://docs.telerik.com/kendo-ui/controls/data-management/grid/adaptive)

**Comment by cwishva** [comment]
When will this be available ?

**Comment by CecoMilchev** [comment]
Also reported in a ticket with ID 1343811.

**Comment by joneff** [comment]
Additionally reported in TID 1146171

**Comment by PreslavKozovski** [comment]
This issue is related to all Sass themes, thus, I am moving it to the kendo-themes repo:
telerik/kendo-themes#384
Please, follow the discussion there.
