### ISSUE TITLE
Setting the columns.filterable.cell.inputwidth property of the Grid does not change the width of the input

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-theme-bootstrap#362]
The DOM element receives the width as an inline style, but the style does not affect the appearance of the input. - http://dojo.telerik.com/AsiGi/2

It is working as expected with the Bootstrap v3 theme:  http://dojo.telerik.com/AmABaV/2

**Comment by theOrlin** [comment]
Also applies to theme default.
