### ISSUE TITLE
On Your Readme, Bad Link for Angular, No React Example

### ISSUE THREAD

**Issue by pkellner** [telerik/kendo-theme-bootstrap#365]
the link on the readme to "Using the Bootstrap Theme in Angular Projects" points to some url with port 4000 and is obviously broken.

No React example

**Comment by gyoshev** [comment]
Thank you for reporting this. Since the original report we have moved all themes to a single repository and [added the missing links there](https://github.com/telerik/kendo-themes/blob/develop/README.md).
