### ISSUE TITLE
Dropdown arrow overlaps with the loading icon

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-theme-bootstrap#366]
The dropdown arrow is not properly displayed when the ComboBox is in loading state:

Pelase check the following sample plunker:

[https://plnkr.co/edit/38zsVKZSSzxlNlyujRDz?p=preview](https://plnkr.co/edit/38zsVKZSSzxlNlyujRDz?p=preview)

**Comment by gyoshev** [comment]
This appears to be fixed in the latest release:

![image](https://user-images.githubusercontent.com/90405/44474954-81290d80-a63c-11e8-826c-cef396ceb135.png)

[StackBlitz snippet](https://stackblitz.com/edit/angular-ozu2db?file=app/app.component.ts).
