### ISSUE TITLE
Input-group doesn't work with class="form-control k-textbox"

### ISSUE THREAD

**Issue by kakone** [telerik/kendo-theme-bootstrap#368]
With the new bootstrap 4.0 input-group, the addon is not on the same line that the input when your add the classes _form-control_ and _k-textbox_.
https://dojo.telerik.com/@kakone/ocAxEC

```
<div class="input-group">
  <div class="input-group-prepend">
    <span class="input-group-text">
      <span class="k-icon k-i-user"></span>
    </span>
  </div>
  <input placeholder="Username" type="text" class="form-control k-textbox" />
</div>
```
![image](https://user-images.githubusercontent.com/1640329/35677987-f7497e44-0751-11e8-979a-fe8a83164b06.png)

**Comment by gyoshev** [comment]
This problem is resolved in the latest versions of the theme package. Here is the [updated plunker](https://dojo.telerik.com/ibutaceV).
