### ISSUE TITLE
Inactive chart labels are invisible

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-bootstrap#44]
The color is set to white which makes them invisible. Can be reproduced in the dashboard demo donut chart.

cc @gyoshev @tsvetomir

**Comment by gyoshev** [comment]
The chart needs the SASS variables serialized ([1](https://github.com/telerik/kendo-theme-default/blob/master/styles/charts/_theme.scss#L17-L43), [2](https://github.com/telerik/kendo-theme-default/blob/master/styles/base/_states.scss#L103-L143)). Ideally, these should be reused across themes -- sharing the file from default.

**Comment by KirilNN** [comment]
Yeah, I think we have them here:

https://github.com/telerik/kendo-theme-bootstrap/commit/88436598471ce4ee0e1c84464f6841d919c9751f

But maybe something is missing.

**Comment by tsvetomir** [comment]
Perhaps [$chart-inactive](https://github.com/telerik/kendo-theme-default/blob/master/styles/charts/_theme.scss#L5) and the related variables.
