### ISSUE TITLE
Implement the same fix for $icon-font-dir from kendo-theme-default

### ISSUE THREAD

**Issue by silvioboehme** [telerik/kendo-theme-bootstrap#51]
Applications generated with angular-cli does not embed find the icon font location.
Thjis is fixed in kendo-theme-default.
https://github.com/telerik/kendo-theme-default/issues/41

**Comment by joneff** [comment]
In the v2 branch for theme-bootstrap, as well as other themes based on theme-default, we'll reference the embedded font from theme-default.
