### ISSUE TITLE
RoadMap or release date

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-theme-bootstrap#53]
Hi to all,
do you have any release date?
we just would like to start using our bootstrap v4 theme with kendo!

**Comment by petyosi** [comment]
Hi @meriturva , 

may you please clarify if you are looking into using the theme with Kendo UI for Angular 2 or with the jQuery suite?

**Comment by meriturva** [comment]
Hi @petyosi we just would like to use it with new Kendo UI for Angular 2

**Comment by petyosi** [comment]
Thank you. We are working on unifying the theme internals with the default sass theme (things happen in the `v2` branch). We don't have a concrete release date yet, though.

**Comment by meriturva** [comment]
Thanks @petyosi for your answer.

Do you think v2 branch is quite stable? do you already have in your internal roadmap many breaking changes? We know that it is not stable product but we already implemented our main bootstrap 4 theme and we would like to start using kendo for angular 2.

Thanks in advice for your comments.

**Comment by meriturva** [comment]
Sorry @petyosi do you have any news about my last comment?

**Comment by CodeRevver** [comment]
I'm interested as well - I'd quite like to start using v2 where possible.  Also noticed they removed this bootstrap theme from the kendo supported themes a few weeks ago.  🤷‍♂️

**Comment by petyosi** [comment]
@meriturva I am afraid that it is a bit too early to comment - at least, the branch is not stable enough to be merged in the master branch. Feel free to try try it, though.

**Comment by meriturva** [comment]
Just last question @petyosi 
do you have v2 branch published on telerik npm repository?

**Comment by petyosi** [comment]
No, we don't have multiple channels currently.
