### ISSUE TITLE
Glitches in Kendo UI for Angular 2 components

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-theme-bootstrap#66]
- [x] ComboBox hover effect is missing
- [x] DropDownList hover effect is missing
- [x] MultiSelect - popup overlaps the bottom border (not sure if this is an actual issue)
- [x] NumericTextBox - spinner icons not aligned
- [x] Upload - files extensions appearance
- [x] Switch - ON handle background; wrong outline
- [x] Calendar - the whole appearance
- [x] Dialog - (Action buttons) - OK button; missing buttons hover effect
- [x] Buttons - primary bare buttons styling
- [x] Panelbar - items hover
- [x] TabStrip - items hover
- [x] MaskedTextBox - missing focus state; wrong border in the jQuery widget
- [x] Charts - series colors - check with @yordanov

**Comment by inikolova** [comment]
Currently dropdownlist does not have k-state-active class. Should we add it?

**Comment by inikolova** [comment]
@joneff , where $nav-tabs-active-link-hover-color, nav-tabs-active-link-hover-bg and $nav-tabs-active-link-hover-border-color are defined?

**Comment by inikolova** [comment]
MaskedTextBox - missing focus state -> Related to https://github.com/telerik/kendo-angular-inputs/issues/91

**Comment by inikolova** [comment]
ComboBox -> @joneff should we decrease the clear icon right position?

**Comment by inikolova** [comment]
Upload -> added styling; should check with @yordanov

**Comment by gyoshev** [comment]
The calendar styling is not inherited from theme-default, inheriting it should fix most of the issues.
